version: "3.1"
name: neurogpt
services:
  back-end: 
    image: nedsearls/ec530-bu:backend.latest
    build:
      context: backend
    ports:
      - 4009:4009
  postgres:
    image: postgres:14-alpine
    ports:
      - 5436:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data    
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=documents
