version: "3.1"
name: project2
services:
  back-end: 
    image: nedsearls/ec530-bu:backend.latest
    build:
      context: backend
    ports:
      - 4009:4009
    env_file:
      - backend/.env
    command: python __init__.py
  postgres:
    image: postgres:14-alpine
    ports:
      - 5436:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data    
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=documents
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 6378:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./rpc_backend:/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - "5673:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
  worker:
    image: nedsearls/ec530-bu:worker.latest
    build:
      context: backend/task_queue
  test:
    image: nedsearls/ec530-bu:backend.latest
    env_file:
      - backend/.env
    command: python3 -m pytest -W ignore::DeprecationWarning
    