version: "3.1"
name: neurogpt
services:
  # back-end:
  #   build:
  #     context: backend
  postgres:
    image: postgres:14-alpine
    ports:
      - 5436:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data    
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=documents
